version: '3.8'

services:
  todo_web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=todo_core.settings
      - DJANGO_SECRET_KEY=django-insecure-d92cq)nht1(hkz9s74no$o==v6x=12^*p!jas9acuwuvo$9h7=
      - DJANGO_DEBUG=False
      - DB_NAME=todo_db
      - DB_USER=todo_user
      - DB_PASSWORD=todo_password
      - DB_HOST=db
      - DB_PORT=5432
    # command: gunicorn todo_core.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: todo_db
    restart: always
    environment:
      - POSTGRES_USER=todo_user
      - POSTGRES_PASSWORD=todo_password
      - POSTGRES_DB=todo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  
